AWSTemplateFormatVersion: "2010-09-09"
Description: Preparing AWS resources form mansplaining.
Parameters: 
  UniqueID: 
    Type: String
    Default: yourinitials
    Description: Enter your initials in lower case as a unique identifier for components created 
    AllowedPattern: "^([a-z]|(d(?!d{0,2}.d{1,3}.d{1,3}.d{1,3})))([a-zd]|(.(?!(.|-)))|(-(?!.))){1,61}[a-zd.]$"

Resources:
  MansplainingS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: BucketOwnerFullControl
      VersioningConfiguration: 
        Status: Enabled
      BucketName:
        Fn::Join:
          - ""
          - - "mansplaining-"
            - !Ref UniqueID
            - "-"
            - !Select
             - 0
             - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"

Outputs:
      MansplainingS3Bucket:
        Description: Mansplaining bucket name
        Value: !Ref MansplainingS3Bucket
        Export :
          Name : MansplainingBucket

      MansplainingS3BucketARN:
        Description: Mansplaining bucket ARN
        Value: !GetAtt [MansplainingS3Bucket,Arn]
        Export:
          Name: MansplainingBucketARN

